# Generated by Django 5.0.1 on 2024-01-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_preparation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_time_unit',
            field=models.CharField(default='', max_length=50),
        ),
    ]
